### ISSUE TITLE
Changing Node from drop-down select fails to update due to 404 URL

### ISSUE THREAD

**Issue by spatula75** [rabbitmq/rabbitmq-top#15]
Observed in RabbitMQ 3.6.5.

When using either the top processes or top ets tables view, upon changing the cluster node from the drop-down select, it was observed that the page did not update.

This turned out to be because the new URL provided by the select results in a 404.  Unlike the URL for the first cluster node, this URL lacks the trailing /20.

Adding the /20 to the end of the new URL results in the page updating and displaying the correct data.  Additionally selecting any different value from the "Rows" drop-down will also result in a redirect that displays the correct data.  So it appears the trouble is related to calculating the correct URL from the combination of the two drop-down selects when only the first one is changed (or at least that is the symptom).

As a workaround, either tack a "/20" onto the end of the URL after changing the Node, or select any alternative value for "Rows" (and optionally change it back).

**Comment by gerhard** [comment]
I have observed this as well, it's a pretty annoying bug. Attempting a quick fix...
