### ISSUE TITLE
3.6.x version of this plugin is not available from Community Plugins

### ISSUE THREAD

**Issue by 62mkv** [rabbitmq/rabbitmq-top#19]
Hi.

The "Downloading" section in a README.md says:

> You can download a pre-built binary of this plugin from RabbitMQ Community plugins page.

But there's no "Download" link for rabbitmq_top on that page!

**Comment by 62mkv** [comment]
By the way, I've found a page on bintray, so that's probably an issue on RabbitMQ website; but may be it's worthy mentioning on the plugin README: https://bintray.com/rabbitmq/community-plugins/rabbitmq_top/v3.5.x#files

**Comment by michaelklishin** [comment]
This plugin is included into RabbitMQ distribution as of 3.6.6 IIRC.

**Comment by 62mkv** [comment]
offtopic: I am having 3.6.5. Is it same to install the abovementioned 3.5.x version ?

**Comment by michaelklishin** [comment]
No, it's not advised that you use the 3.5.x version. This plugin ships with RabbitMQ [as of 3.6.3](https://github.com/rabbitmq/rabbitmq-server/issues/852).

**Comment by 62mkv** [comment]
it appears that the plugin version for 3.6.5 already was available in the /plugins folder, it just has to be enabled. Still I see an improvement of README possible (it's simply misleading right now).

**Comment by michaelklishin** [comment]
@62mkv I'd agree that it is incomplete but it is not misleading. I've updated it either way. Thanks for reporting.

**Comment by 62mkv** [comment]
@michaelklishin This is *much* better, thanks, Michael !
